language: haskell

ghc:
  - 7.0
  - 7.2
  - 7.4
  - 7.6
  - 7.8
  - 7.10

install:
  - ghc --version
  - cabal --version
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks && cabal build && cabal test --show-details=always && cabal bench
